### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by owiecc** [Wikunia/ConstraintSolver.jl#127]
My proposal for the package logo. 
![ConstraintSolver jl logo](https://user-images.githubusercontent.com/6896639/78713455-99859300-791a-11ea-81ee-100588e6d8db.png)

**Comment by Wikunia** [comment]
Thanks for the fast suggestion @owiecc . Somehow the green circle looks a bit angry :smiley: 
I like the julia colors in there and the ordering reminds me of a three nodes which maybe can be used as a small branching tree. :thinking:

**Comment by Wikunia** [comment]
This is my current draft
![Logo](https://user-images.githubusercontent.com/4931746/78772894-b9589d80-7992-11ea-80f4-9b2580de4cb6.png)

**Comment by pdimens** [comment]
How's this for a mockup? Kinda combines both your ideas (the font choice is just a placeholder):
![image](https://user-images.githubusercontent.com/19176506/80983949-d6965580-8df2-11ea-9fe1-218f9c960d6e.png)

**Comment by Wikunia** [comment]
Thanks for the mockup. Came here from slack? :smile: 
I like the simplicity of the top right one. That might even work for a small favicon. 
How did you make them? Would love to get svgs of them.
Thanks again!

**Comment by pdimens** [comment]
Yeah, I saw you post in the slack. I made all my graphics with inkscape. I've attached the source SVG. I'd strongly suggest changing the font b/c it just doesn't feel right.
[constraintsolverjl.zip](https://github.com/Wikunia/ConstraintSolver.jl/files/4575624/constraintsolverjl.zip)

**Comment by ccoffrin** [comment]
Random suggestion, consider the slightly different shade for the circle border, this is part of the current Julia logo.

**Comment by cormullion** [comment]
For the square logo, here's something very simple:

<img width="253" alt="Screenshot 2020-05-04 at 17 31 55" src="https://user-images.githubusercontent.com/52289/80989704-39a4de00-8e2d-11ea-9fbb-2fad242342d2.png">

**Comment by cormullion** [comment]
BTW - Julia color definitions are [here](https://github.com/JuliaLang/julia-logo-graphics).

**Comment by Wikunia** [comment]
![gravit](https://user-images.githubusercontent.com/4931746/83634125-4e969d80-a5a2-11ea-81c8-e69baa5a6235.png)


My latest one. Thanks for the colors @cormullion and the overall layout of @pdimens

**Comment by pdimens** [comment]
Love it! That's a very dashing font, which is it?

**Comment by Wikunia** [comment]
Thanks man. I used your design in https://designer.gravit.io/ .
The name of the font is ... "Average" :rofl:

**Comment by pdimens** [comment]
Such an awful name for such a nice font. Thanks for sharing the name, I might use it for a research poster!
