### ISSUE TITLE
Open for renaming

### ISSUE THREAD

**Issue by Wikunia** [Wikunia/ConstraintSolver.jl#40]
I'm thinking about renaming the package as it would sound like it's THE package for constraint programming if it gets an actual julia package. Some of you might know that I'm terrible at naming things... And yes currently there is no other constraint solver julia package but nevertheless it should be up for discussion here.
Based on previous help: Do you have some ideas @ccoffrin @shibumi ?
Current ideas:
- CPS.jl
- CoPS.jl
- CoPra.jl
- ConstraintProgramming.jl by @rschwarz

**Comment by shibumi** [comment]
I would go for `CoPra.jl`, but `CoPS.jl` is funny as well. Both would provide nice ideas for fancy logos. If your project don't have a fancy logo, it sucks. That's the rule nowadays :P 

![https://i.imgflip.com/3ecohj.jpg](https://i.imgflip.com/3ecohj.jpg)

**Comment by metanoid** [comment]
ConstraintProgramming.jl would be the clearest and most beginner-friendly choice.

**Comment by ccoffrin** [comment]
I think `ConstraintSolver.jl`, is an ok name.  I think my first choice would be `CSPSolver.jl` (see [CSP](https://en.wikipedia.org/wiki/Constraint_satisfaction_problem)).  The term CSP is widely recongized by the CP community and I think this name is fairly consistent with the names of other MOI solvers.  Reviewing the naming trends of [other CP projects](https://en.wikipedia.org/wiki/Constraint_programming#Constraint_programming_libraries_for_general-purpose_programming_languages), I didn't find a clear naming convention that you could piggy back on.

I do feel that `ConstraintProgramming.jl` is too general, it would be analogous to calling the Gurobi something like, `MixedIntegerProgramming.jl`.

**Comment by Wikunia** [comment]
Thanks for your comments. Regarding CSP: This would limit it to satisfaction problems, right? The goal is to be able to also have the choice to give an objective function. Therefore maybe `CPSolver.jl` ?

**Comment by ccoffrin** [comment]
I would not say that CSPSolver would limit you to only problems without an objective.  In my mind CSP means variables with finite domains and a white-box solver with a focus on combinatorial constraints.

**Comment by Wikunia** [comment]
It's now a registered package and I used the name ConstraintSolver.jl :smile:
