### ISSUE TITLE
Confusion between values and indices

### ISSUE THREAD

**Issue by matbesancon** [Wikunia/ConstraintSolver.jl#56]
It might be due to the solver being tested first on Sudoku instances. When testing the solver on problems with non-integer coefficients, some errors occur, which can be fixed by widening the types.

However, in some places of the code, the value and index spaces are mixed up. An example with the `has` function:

```julia
function has(v::CS.Variable, x::Int)
    if x > v.max || x < v.min
        return false
    end
    ind = v.indices[x + v.offset]
    return v.first_ptr <= ind <= v.last_ptr
end
```
In the first part, x is used as a value, checking if the variable is between min and max. But in the second part, it is used as an index as `x + v.offset`. Using values and indices interchangeably will lead to bugs later (what if you have infinite, if you have float coefficients, etc).

**Comment by Wikunia** [comment]
Floating coefficients shouldn't affect the discrete variables, right? I think for non discrete or unbounded variables (which don't exist yet) a different variable type might need to exist. 
Not sure how to rewrite it otherwise without loosing performance on these operations.

**Comment by matbesancon** [comment]
Yes they can affect them, even for pure integer variables, you can have
floating constraints a^T x <= b with a non-integral

**Comment by matbesancon** [comment]
The problem is explained in more detail in https://en.wikipedia.org/wiki/Independent_set_(graph_theory)

**Comment by Wikunia** [comment]
I think this can be closed if I take care that only discrete variables get checked here, right?

**Comment by matbesancon** [comment]
Yup all right :)
